FROM golang:1.23-alpine AS builder

ARG SERVICE_NAME
ARG SERVICE_PORT

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ${SERVICE_NAME} ./cmd/${SERVICE_NAME}

FROM alpine:latest

ARG SERVICE_NAME
ARG SERVICE_PORT

ENV BIN=/app/${SERVICE_NAME}

WORKDIR /app

COPY --from=builder ${BIN} .

EXPOSE ${SERVICE_PORT}

CMD ${BIN}
