FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o {{ .Env.SERVICE_NAME }} ./cmd/{{ .Env.SERVICE_NAME }}

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/{{ .Env.SERVICE_NAME }} .

EXPOSE {{ .Env.SERVICE_PORT }}

CMD ["./{{ .Env.SERVICE_NAME }}"]
