version: "3"
env:
  DB_DIALECT: postgres
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: bookly
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_SILENCE_LOGGER: true

tasks:
  run:
    cmds:
      - go run cmd/api/main.go
  test:
    cmds:
      - go test -v ./...
  fmt:
    cmds:
      - gofmt -s -w -l .
      - goimports -w -local github.com/omegaatt36/bookly $(find . -type f -name '*.go')
      - gci write -s standard -s default -s "Prefix(github.com/omegaatt36/bookly)" --skip-generated .
      - go mod tidy
  lint:
    cmds:
      - revive -formatter friendly -config revive.toml  ./...
      - find . -name "*.json" | xargs -n 1 -t gojq . > /dev/null
      - go vet -all ./...
      - misspell -error */**
      - staticcheck $(go list ./...)
  setup-db:
    desc: Setup the database
    cmds:
      - docker compose -f deploy/dev/docker-compose.yaml up -d
  remove-db:
    desc: Remove the database
    cmds:
      - docker compose -f deploy/dev/docker-compose.yaml down
  migrate-api:
    cmds:
      - go run cmd/api-dbmigration/main.go
