FROM ubuntu:24.04

ARG TARGETARCH

COPY bin/linux_${TARGETARCH} /usr/local/bin/

RUN apt update && apt install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PATH="/usr/local/bin:${PATH}"
