// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: ledger.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createLedger = `-- name: CreateLedger :exec
INSERT INTO ledgers (
    account_id,
    date,
    type,
    amount,
    note,
    is_adjustment,
    adjusted_from
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateLedgerParams struct {
	AccountID    string
	Date         pgtype.Timestamptz
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	IsAdjustment bool
	AdjustedFrom pgtype.UUID
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) error {
	_, err := q.db.Exec(ctx, createLedger,
		arg.AccountID,
		arg.Date,
		arg.Type,
		arg.Amount,
		arg.Note,
		arg.IsAdjustment,
		arg.AdjustedFrom,
	)
	return err
}

const getLedgerAmount = `-- name: GetLedgerAmount :one
SELECT amount FROM ledgers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetLedgerAmount(ctx context.Context, id string) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getLedgerAmount, id)
	var amount decimal.Decimal
	err := row.Scan(&amount)
	return amount, err
}

const getLedgerByID = `-- name: GetLedgerByID :one
SELECT 
    l.id, l.created_at, l.updated_at, l.account_id, l.date, l.type, l.amount, l.note, l.is_adjustment, l.adjusted_from, l.is_voided, l.voided_at,
    a.currency
FROM ledgers l
JOIN accounts a ON l.account_id = a.id
WHERE l.id = $1
LIMIT 1
`

type GetLedgerByIDRow struct {
	ID           string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	AccountID    string
	Date         pgtype.Timestamptz
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	IsAdjustment bool
	AdjustedFrom pgtype.UUID
	IsVoided     bool
	VoidedAt     pgtype.Timestamptz
	Currency     string
}

func (q *Queries) GetLedgerByID(ctx context.Context, id string) (GetLedgerByIDRow, error) {
	row := q.db.QueryRow(ctx, getLedgerByID, id)
	var i GetLedgerByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Date,
		&i.Type,
		&i.Amount,
		&i.Note,
		&i.IsAdjustment,
		&i.AdjustedFrom,
		&i.IsVoided,
		&i.VoidedAt,
		&i.Currency,
	)
	return i, err
}

const getLedgersByAccountID = `-- name: GetLedgersByAccountID :many
SELECT 
    l.id, l.created_at, l.updated_at, l.account_id, l.date, l.type, l.amount, l.note, l.is_adjustment, l.adjusted_from, l.is_voided, l.voided_at,
    a.currency
FROM ledgers l
JOIN accounts a ON l.account_id = a.id
WHERE l.account_id = $1
ORDER BY l.date DESC, l.updated_at DESC
`

type GetLedgersByAccountIDRow struct {
	ID           string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	AccountID    string
	Date         pgtype.Timestamptz
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	IsAdjustment bool
	AdjustedFrom pgtype.UUID
	IsVoided     bool
	VoidedAt     pgtype.Timestamptz
	Currency     string
}

func (q *Queries) GetLedgersByAccountID(ctx context.Context, accountID string) ([]GetLedgersByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, getLedgersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLedgersByAccountIDRow{}
	for rows.Next() {
		var i GetLedgersByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
			&i.Date,
			&i.Type,
			&i.Amount,
			&i.Note,
			&i.IsAdjustment,
			&i.AdjustedFrom,
			&i.IsVoided,
			&i.VoidedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedger = `-- name: UpdateLedger :exec
UPDATE ledgers 
SET 
    date = CASE WHEN $1::timestamptz IS NULL THEN date ELSE $1 END,
    type = CASE WHEN $2::text IS NULL THEN type ELSE $2 END,
    amount = CASE WHEN $3::decimal IS NULL THEN amount ELSE $3 END,
    note = CASE WHEN $4::text IS NULL THEN note ELSE $4 END,
    updated_at = NOW()
WHERE id = $5
`

type UpdateLedgerParams struct {
	Date   pgtype.Timestamptz
	Type   pgtype.Text
	Amount pgtype.Numeric
	Note   pgtype.Text
	ID     string
}

func (q *Queries) UpdateLedger(ctx context.Context, arg UpdateLedgerParams) error {
	_, err := q.db.Exec(ctx, updateLedger,
		arg.Date,
		arg.Type,
		arg.Amount,
		arg.Note,
		arg.ID,
	)
	return err
}

const voidLedger = `-- name: VoidLedger :exec
UPDATE ledgers 
SET 
    is_voided = true,
    voided_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) VoidLedger(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidLedger, id)
	return err
}
