// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserID    string
	Name      string
	Status    string
	Currency  string
	Balance   decimal.Decimal
}

type Identity struct {
	ID         int32
	UserID     string
	Provider   string
	Identifier string
	Credential string
	LastUsedAt pgtype.Timestamptz
}

type Ledger struct {
	ID           string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	AccountID    string
	Date         pgtype.Timestamptz
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	IsAdjustment bool
	AdjustedFrom pgtype.UUID
	IsVoided     bool
	VoidedAt     pgtype.Timestamptz
}

type RecurringTransaction struct {
	ID           string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	UserID       string
	AccountID    string
	Name         string
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	RecurType    string
	Status       string
	Frequency    int32
	DayOfWeek    pgtype.Int4
	DayOfMonth   pgtype.Int4
	MonthOfYear  pgtype.Int4
	LastExecuted pgtype.Timestamptz
	NextDue      pgtype.Timestamptz
}

type Reminder struct {
	ID                     string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	RecurringTransactionID string
	ReminderDate           pgtype.Timestamptz
	IsRead                 bool
	ReadAt                 pgtype.Timestamptz
}

type User struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Disabled  bool
	Name      string
	Nickname  pgtype.Text
}
