// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UserID    string
	Name      string
	Status    string
	Currency  string
	Balance   decimal.Decimal
}

type Identity struct {
	ID         int32
	UserID     string
	Provider   string
	Identifier string
	Credential string
	LastUsedAt pgtype.Timestamptz
}

type Ledger struct {
	ID           string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	AccountID    string
	Date         pgtype.Timestamptz
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	IsAdjustment bool
	AdjustedFrom pgtype.UUID
	IsVoided     bool
	VoidedAt     pgtype.Timestamptz
}

type User struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Disabled  bool
	Name      string
	Nickname  pgtype.Text
}
