// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	UserID    int32
	Name      string
	Status    string
	Currency  string
	Balance   decimal.Decimal
}

type BankAccount struct {
	ID            int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	AccountID     int32
	AccountNumber string
	BankName      string
	BranchName    pgtype.Text
	SwiftCode     pgtype.Text
}

type Identity struct {
	ID         int32
	UserID     int32
	Provider   string
	Identifier string
	Credential string
	LastUsedAt pgtype.Timestamptz
}

type Ledger struct {
	ID           int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	AccountID    int32
	Date         pgtype.Timestamptz
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	IsAdjustment bool
	AdjustedFrom pgtype.Int4
	IsVoided     bool
	VoidedAt     pgtype.Timestamptz
}

type RecurringTransaction struct {
	ID           int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	UserID       int32
	AccountID    int32
	Name         string
	Type         string
	Amount       decimal.Decimal
	Note         pgtype.Text
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
	RecurType    string
	Status       string
	Frequency    int32
	DayOfWeek    pgtype.Int4
	DayOfMonth   pgtype.Int4
	MonthOfYear  pgtype.Int4
	LastExecuted pgtype.Timestamptz
	NextDue      pgtype.Timestamptz
}

type Reminder struct {
	ID                     int32
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	RecurringTransactionID int32
	ReminderDate           pgtype.Timestamptz
	IsRead                 bool
	ReadAt                 pgtype.Timestamptz
}

type User struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Disabled  bool
	Name      string
	Nickname  pgtype.Text
}
