// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"context"

	"github.com/shopspring/decimal"
)

type Querier interface {
	AddIdentity(ctx context.Context, arg AddIdentityParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateLedger(ctx context.Context, arg CreateLedgerParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	DeactivateAccountByID(ctx context.Context, arg DeactivateAccountByIDParams) error
	DeactivateUserByID(ctx context.Context, id string) error
	DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) error
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetAccountsByUserID(ctx context.Context, userID string) ([]Account, error)
	GetAllAccounts(ctx context.Context) ([]Account, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetIdentitiesByUserID(ctx context.Context, userID string) ([]Identity, error)
	GetIdentityByProviderAndIdentifier(ctx context.Context, arg GetIdentityByProviderAndIdentifierParams) (Identity, error)
	GetLedgerAmount(ctx context.Context, id string) (decimal.Decimal, error)
	GetLedgerByID(ctx context.Context, id string) (GetLedgerByIDRow, error)
	GetLedgersByAccountID(ctx context.Context, accountID string) ([]GetLedgersByAccountIDRow, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (GetUserByIdentityRow, error)
	IncreaseAccountBalance(ctx context.Context, arg IncreaseAccountBalanceParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateIdentityCredential(ctx context.Context, arg UpdateIdentityCredentialParams) error
	UpdateIdentityLastUsed(ctx context.Context, arg UpdateIdentityLastUsedParams) error
	UpdateLedger(ctx context.Context, arg UpdateLedgerParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	VoidLedger(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
