name: Build and push Docker image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  set-timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set-timestamp.outputs.timestamp }}
    steps:
      - id: set-timestamp
        run: echo "timestamp=$(date +%Y-%m-%dT%H_%M_%S)" >> $GITHUB_OUTPUT

  build-images:
    needs: set-timestamp
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, web, api-dbmigration]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.template
          push: true
          tags: |
            docker.io/omegaatt36/bookly-${{ matrix.service }}:${{ needs.set-timestamp.outputs.timestamp }}
            docker.io/omegaatt36/bookly-${{ matrix.service }}:latest
          build-args: |
            SERVICE_NAME=${{ matrix.service }}
            SERVICE_PORT=${{ matrix.service == 'web' && '3000' || '8080' }}
