name: Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt-and-lint:
    runs-on: ubuntu-latest
    container: omegaatt36/bookly-lint:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run fmt
        run: task fmt

      - name: Run lint
        run: task lint

      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Code is not properly formatted. Please run 'task fmt' locally and commit the changes."
            exit 1
          fi
