name: Code Quality Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/daixiang0/gci@latest
          go install github.com/mgechev/revive@latest
          go install github.com/itchyny/gojq/cmd/gojq@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/client9/misspell/cmd/misspell@latest

      - name: Run fmt
        run: task fmt

      - name: Run lint
        run: task lint

      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Code is not properly formatted. Please run 'task fmt' locally and commit the changes."
            exit 1
          fi
